version: "3.7"

services:
  ########################################################################
  ####                     API SERVICE                                ####
  ########################################################################
  notipy-api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      /bin/sh -c "
      poetry run uvicorn main:app --reload --host 0.0.0.0;
      "
    volumes:
      - .:/app
      - ./volumes:/volumes:ro
    env_file:
      - .env
    networks:
      - notipy

  ########################################################################
  ####                    DATABASE SERVICE                            ####
  ########################################################################
  mongodb:
    image: mongo:4.4.0-rc7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb/:/data/db/
    networks:
      - notipy

  ########################################################################
  ####                     WORKER SERVICE                             ####
  ########################################################################
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run celery -A worker.send_notification worker -l info
    networks:
      - notipy

  ########################################################################
  ####                     MESSAGE QUEUE SERVICE                      ####
  #######################################################################
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
      - RABBITMQ_DEFAULT_VHOST=notipy
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - notipy

  ########################################################################
  ####                     BUCKET SERVICE                        #######
  #######################################################################
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./volumes/minio/data:/export
      - ./volumes/minio/config:/root/.minio
    command: server --console-address :9001 /export
    networks:
      - notipy

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      apk add --no-cache bash;
      /usr/bin/mc config host add myminio http://minio:9000 minio password;
      /usr/bin/mc mb myminio/attachments;
      /usr/bin/mc anonymous set public myminio/attachments;
      exit 0;
      "
    networks:
      - notipy

networks:
  notipy:
